import { MenuItem } from './menu.model';

export const MENU: MenuItem[] = [
  {
    id: 1,
    label: 'Navegacao',
    isTitle: true,
  },
  {
    id: 10,
    label: 'Dashboard',
    icon: 'ph-gauge',
    link: '/jm/dashboard',
    permissionKey: 'dashboard.executive.view',
  },
  {
    id: 20,
    label: 'Atendimento',
    icon: 'ph-calendar-check',
    permissionKeys: [
      'commercial.leads.view',
      'reception.visits-agenda.view',
      'reception.visits-register.view',
    ],
    subItems: [
      {
        id: 21,
        label: 'Leads',
        parentId: 20,
        permissionKey: 'commercial.leads.view',
        subItems: [
          {
            id: 211,
            label: 'Listagem',
            link: '/jm/atendimento/leads/listagem',
            parentId: 21,
            permissionKey: 'commercial.leads.view',
          },
        ],
      },
      {
        id: 22,
        label: 'Agendamento',
        link: '/jm/atendimento/agendamento',
        parentId: 20,
        permissionKey: 'reception.visits-agenda.view',
      },
    ],
  },
  {
    id: 30,
    label: 'Vendas',
    icon: 'ph-handshake',
    permissionKeys: [
      'customers.customers.view',
      'commercial.overview.view',
      'commercial.proposals.view',
      'commercial.sales.view',
    ],
    subItems: [
      {
        id: 31,
        label: 'Clientes',
        link: '/jm/clientes',
        parentId: 30,
        permissionKey: 'customers.customers.view',
      },
      {
        id: 32,
        label: 'Visao Geral',
        link: '/jm/vendas/visao-geral',
        parentId: 30,
        permissionKey: 'commercial.overview.view',
      },
      {
        id: 33,
        label: 'Propostas',
        link: '/jm/vendas/propostas',
        parentId: 30,
        permissionKey: 'commercial.proposals.view',
      },
      {
        id: 34,
        label: 'Desistencias',
        link: '/jm/vendas/desistencias',
        parentId: 30,
        permissionKey: 'commercial.sales.view',
      },
    ],
  },
  {
    id: 40,
    label: 'Empreendimentos',
    icon: 'ph-buildings',
    permissionKeys: [
      'enterprises.builders.view',
      'enterprises.projects.view',
      'enterprises.units.view',
    ],
    subItems: [
      {
        id: 41,
        label: 'Construtoras',
        link: '/jm/construtora',
        parentId: 40,
        permissionKey: 'enterprises.builders.view',
      },
      {
        id: 42,
        label: 'Empreendimentos',
        link: '/jm/empreendimentos',
        parentId: 40,
        permissionKey: 'enterprises.projects.view',
      },
      {
        id: 43,
        label: 'Unidades',
        link: '/jm/unidades',
        parentId: 40,
        permissionKey: 'enterprises.units.view',
      },
    ],
  },
  {
    id: 50,
    label: 'Clientes',
    icon: 'ph-users',
    link: '/jm/clientes',
    permissionKey: 'customers.customers.view',
  },
  {
    id: 60,
    label: 'Financas',
    icon: 'ph-wallet',
    permissionKeys: [
      'finance.accounts-receivable.view',
      'finance.accounts-payable.view',
      'finance.reports.view',
      'finance.cash-flow.view',
      'finance.projection.view',
    ],
    subItems: [
      {
        id: 61,
        label: 'Contas a Receber',
        link: '/jm/financeiro/contas-receber',
        parentId: 60,
        permissionKey: 'finance.accounts-receivable.view',
      },
      {
        id: 62,
        label: 'Contas a Pagar',
        link: '/jm/financeiro/contas-pagar',
        parentId: 60,
        permissionKey: 'finance.accounts-payable.view',
      },
      {
        id: 63,
        label: 'DRE',
        link: '/jm/financeiro/dre',
        parentId: 60,
        permissionKey: 'finance.reports.view',
      },
      {
        id: 64,
        label: 'Fluxo de Caixa',
        link: '/jm/financeiro/fluxo-caixa',
        parentId: 60,
        permissionKey: 'finance.cash-flow.view',
      },
      {
        id: 65,
        label: 'Projecao',
        link: '/jm/financeiro/projecao',
        parentId: 60,
        permissionKey: 'finance.projection.view',
      },
    ],
  },
  {
    id: 70,
    label: 'RH',
    icon: 'ph-user-gear',
    permissionKeys: [
      'hr.staff-control.view',
      'hr.absences.view',
      'hr.payroll.view',
      'hr.vacations.view',
      'hr.uniforms.view',
    ],
    subItems: [
      {
        id: 71,
        label: 'Controle de Funcionarios',
        link: '/jm/rh/controle-funcionarios',
        parentId: 70,
        permissionKey: 'hr.staff-control.view',
      },
      {
        id: 72,
        label: 'Controle de Faltas',
        link: '/jm/rh/controle-faltas',
        parentId: 70,
        permissionKey: 'hr.absences.view',
      },
      {
        id: 73,
        label: 'Folha de Pagamentos',
        link: '/jm/rh/folha-pagamentos',
        parentId: 70,
        permissionKey: 'hr.payroll.view',
      },
      {
        id: 74,
        label: 'Ferias',
        link: '/jm/rh/ferias',
        parentId: 70,
        permissionKey: 'hr.vacations.view',
      },
      {
        id: 75,
        label: 'Controle de Uniforme',
        link: '/jm/rh/controle-uniforme',
        parentId: 70,
        permissionKey: 'hr.uniforms.view',
      },
    ],
  },
  {
    id: 80,
    label: 'Administracao',
    icon: 'ph-gear-six',
    permissionKeys: [
      'admin.users.view',
      'admin.profiles.view',
      'admin.permissions.view',
      'admin.general-settings.view',
    ],
    subItems: [
      {
        id: 81,
        label: 'Usuarios',
        link: '/jm/settings',
        parentId: 80,
        permissionKey: 'admin.users.view',
      },
      {
        id: 82,
        label: 'Perfis',
        link: '/jm/settings',
        parentId: 80,
        permissionKey: 'admin.profiles.view',
      },
      {
        id: 83,
        label: 'Permissoes',
        link: '/jm/settings',
        parentId: 80,
        permissionKey: 'admin.permissions.view',
      },
      {
        id: 84,
        label: 'Gerais',
        link: '/jm/settings',
        parentId: 80,
        permissionKey: 'admin.general-settings.view',
      },
    ],
  },
];
