import { MenuItem } from './menu.model';

export const MENU: MenuItem[] = [
  {
    id: 1,
    label: 'Navegacao',
    isTitle: true,
  },
  {
    id: 10,
    label: 'Dashboard',
    icon: 'ph-gauge',
    link: '/jm/dashboard',
    permissionKey: 'dashboard.visualizar',
  },
  {
    id: 20,
    label: 'ATENDIMENTO',
    icon: 'ph-calendar-check',
    permissionKeys: [
      'atendimento.leads.visualizar',
      'atendimento.clientes.visualizar',
      'atendimento.agendamento.visualizar',
    ],
    subItems: [
      {
        id: 21,
        label: 'Leads',
        link: '/jm/atendimento/leads/listagem',
        parentId: 20,
        permissionKey: 'atendimento.leads.visualizar',
      },
      {
        id: 22,
        label: 'Agendamento',
        link: '/jm/atendimento/agendamento',
        parentId: 20,
        permissionKey: 'atendimento.agendamento.visualizar',
      },
      {
        id: 23,
        label: 'Clientes',
        link: '/jm/clientes',
        parentId: 20,
        permissionKey: 'atendimento.clientes.visualizar',
      },
    ],
  },
  {
    id: 40,
    label: 'NEGOCIOS',
    icon: 'ph-buildings',
    permissionKeys: [
      'cadastros.construtoras.visualizar',
      'cadastros.empreendimentos.visualizar',
      'vendas.espelho.visualizar',
    ],
    subItems: [
      {
        id: 41,
        label: 'Construtoras',
        link: '/jm/cadastros/construtoras',
        parentId: 40,
        permissionKey: 'cadastros.construtoras.visualizar',
      },
      {
        id: 42,
        label: 'Empreendimentos',
        link: '/jm/cadastros/empreendimentos',
        parentId: 40,
        permissionKey: 'cadastros.empreendimentos.visualizar',
      },
      {
        id: 43,
        label: 'Unidades',
        link: '/jm/vendas/gerenciamento-unidades',
        parentId: 40,
        permissionKey: 'vendas.unidades.visualizar',
      },
      {
        id: 44,
        label: 'Espelho de Vendas',
        link: '/jm/vendas/espelho',
        parentId: 40,
        permissionKey: 'vendas.espelho.visualizar',
      },
    ],
  },
  {
    id: 30,
    label: 'COMERCIAL',
    icon: 'ph-handshake',
    permissionKeys: [
      'vendas.dashboard.visualizar',
      'vendas.propostas.visualizar',
      'vendas.vendas.visualizar',
    ],
    subItems: [
      {
        id: 31,
        label: 'Visao Geral',
        link: '/jm/vendas/dashboard',
        parentId: 30,
        permissionKey: 'vendas.dashboard.visualizar',
      },
      {
        id: 33,
        label: 'Propostas',
        link: '/jm/vendas/propostas',
        parentId: 30,
        permissionKey: 'vendas.propostas.visualizar',
      },
      {
        id: 35,
        label: 'Contratos',
        parentId: 30,
        disabled: true,
        alwaysVisible: true,
        badge: 'Interno',
      },
      {
        id: 36,
        label: 'Vendas',
        link: '/jm/vendas/vendas',
        parentId: 30,
        disabled: false,
        permissionKey: 'vendas.vendas.visualizar',
      },
      {
        id: 37,
        label: 'Cancelamentos',
        link: '/jm/vendas/desistencias',
        parentId: 30,
        permissionKey: 'vendas.cancelamentos.visualizar',
      },
    ],
  },
  {
    id: 60,
    label: 'FINANCAS',
    icon: 'ph-wallet',
    permissionKeys: [
      'financeiro.contas_receber.visualizar',
      'financeiro.contas_pagar.visualizar',
      'financeiro.dre.visualizar',
      'financeiro.fluxo_caixa.visualizar',
      'financeiro.comissoes.visualizar',
    ],
    subItems: [
      {
        id: 61,
        label: 'Contas a Receber',
        link: '/jm/financeiro/contas-receber',
        parentId: 60,
        permissionKey: 'financeiro.contas_receber.visualizar',
      },
      {
        id: 62,
        label: 'Contas a Pagar',
        link: '/jm/financeiro/contas-pagar',
        parentId: 60,
        permissionKey: 'financeiro.contas_pagar.visualizar',
      },
      {
        id: 63,
        label: 'DRE',
        link: '/jm/financeiro/dre',
        parentId: 60,
        permissionKey: 'financeiro.dre.visualizar',
      },
        {
          id: 64,
          label: 'Fluxo de Caixa',
          link: '/jm/financeiro/fluxo-caixa',
          parentId: 60,
          permissionKey: 'financeiro.fluxo_caixa.visualizar',
        },
      {
        id: 70,
        label: 'Comissoes',
        link: '/jm/financeiro/comissoes',
        parentId: 60,
        permissionKey: 'financeiro.comissoes.visualizar',
      },
    ],
  },
  {
    id: 80,
    label: 'RH',
    icon: 'ph-user-gear',
    permissionKeys: [
      'rh.colaboradores.visualizar',
      'rh.faltas.visualizar',
      'rh.folha_pagamentos.visualizar',
      'rh.ferias.visualizar',
      'rh.uniformes.visualizar',
    ],
    subItems: [
      {
        id: 81,
        label: 'Colaboradores',
        link: '/jm/rh/controle-funcionarios',
        parentId: 80,
        permissionKey: 'rh.colaboradores.visualizar',
      },
      {
        id: 82,
        label: 'Controle de Faltas',
        link: '/jm/rh/controle-faltas',
        parentId: 80,
        permissionKey: 'rh.faltas.visualizar',
      },
      {
        id: 83,
        label: 'Folha de Pagamentos',
        link: '/jm/rh/folha-pagamentos',
        parentId: 80,
        permissionKey: 'rh.folha_pagamentos.visualizar',
      },
      {
        id: 84,
        label: 'Ferias',
        link: '/jm/rh/ferias',
        parentId: 80,
        permissionKey: 'rh.ferias.visualizar',
      },
      {
        id: 85,
        label: 'Controle de Uniforme',
        link: '/jm/rh/controle-uniforme',
        parentId: 80,
        permissionKey: 'rh.uniformes.visualizar',
      },
    ],
  },
  {
    id: 90,
    label: 'Administracao',
    icon: 'ph-gear-six',
    permissionKeys: [
      'administracao.usuarios.visualizar',
      'administracao.perfis_acessos.visualizar',
      'administracao.parametros.visualizar',
      'administracao.gerais.visualizar',
    ],
    subItems: [
      {
        id: 91,
        label: 'Gerais',
        link: '/jm/settings',
        parentId: 90,
        permissionKey: 'administracao.gerais.visualizar',
      },
      {
        id: 93,
        label: 'Perfis e Acessos',
        link: '/jm/configuracoes/perfis-acessos',
        parentId: 90,
        permissionKey: 'administracao.perfis_acessos.visualizar',
      },
      {
        id: 94,
        label: 'Parametros do Sistema',
        parentId: 90,
        disabled: true,
        alwaysVisible: true,
        badge: 'Interno',
      },
    ],
  },
];
