import { MenuItem } from './menu.model';

export const MENU: MenuItem[] = [
  {
    id: 1,
    label: 'Navegacao',
    isTitle: true,
  },
  {
    id: 10,
    label: 'Dashboard',
    icon: 'ph-gauge',
    link: '/jm/dashboard',
    permissionKey: 'dashboard.executive.view',
  },
  {
    id: 20,
    label: 'ATENDIMENTO',
    icon: 'ph-calendar-check',
    permissionKeys: [
      'commercial.leads.view',
      'customers.customers.view',
      'reception.visits-agenda.view',
    ],
    subItems: [
      {
        id: 21,
        label: 'Leads',
        link: '/jm/atendimento/leads/listagem',
        parentId: 20,
        permissionKey: 'commercial.leads.view',
      },
      {
        id: 22,
        label: 'Agendamento',
        link: '/jm/atendimento/agendamento',
        parentId: 20,
        permissionKey: 'reception.visits-agenda.view',
      },
      {
        id: 23,
        label: 'Clientes',
        link: '/jm/clientes',
        parentId: 20,
        permissionKey: 'customers.customers.view',
      },
    ],
  },
  {
    id: 40,
    label: 'NEGOCIOS',
    icon: 'ph-buildings',
    permissionKeys: [
      'enterprises.builders.view',
      'enterprises.projects.view',
      'enterprises.units.view',
    ],
    subItems: [
      {
        id: 41,
        label: 'Construtoras',
        link: '/jm/cadastros/construtoras',
        parentId: 40,
        permissionKey: 'enterprises.builders.view',
      },
      {
        id: 42,
        label: 'Empreendimentos',
        link: '/jm/cadastros/empreendimentos',
        parentId: 40,
        permissionKey: 'enterprises.projects.view',
      },
      {
        id: 43,
        label: 'Unidades',
        link: '/jm/vendas/gerenciamento-unidades',
        parentId: 40,
        permissionKey: 'enterprises.units.view',
      },
      {
        id: 44,
        label: 'Espelho de Vendas',
        link: '/jm/vendas/espelho',
        parentId: 40,
        permissionKey: 'enterprises.units.view',
      },
    ],
  },
  {
    id: 30,
    label: 'COMERCIAL',
    icon: 'ph-handshake',
    permissionKeys: [
      'commercial.overview.view',
      'commercial.proposals.view',
      'commercial.sales.view',
    ],
    subItems: [
      {
        id: 31,
        label: 'Visao Geral',
        link: '/jm/vendas/dashboard',
        parentId: 30,
        permissionKey: 'commercial.overview.view',
      },
      {
        id: 33,
        label: 'Propostas',
        link: '/jm/vendas/propostas',
        parentId: 30,
        permissionKey: 'commercial.proposals.view',
      },
      {
        id: 35,
        label: 'Contratos',
        parentId: 30,
        disabled: true,
        alwaysVisible: true,
        badge: 'Interno',
      },
      {
        id: 36,
        label: 'Vendas',
        link: '/jm/vendas/vendas',
        parentId: 30,
        disabled: false,
        alwaysVisible: true,
      },
      {
        id: 37,
        label: 'Cancelamentos',
        link: '/jm/vendas/desistencias',
        parentId: 30,
        permissionKey: 'commercial.sales.view',
      },
    ],
  },
  {
    id: 60,
    label: 'FINANCAS',
    icon: 'ph-wallet',
    permissionKeys: [
      'finance.accounts-receivable.view',
      'finance.accounts-payable.view',
      'finance.reports.view',
      'finance.cash-flow.view',
      'commercial.results.view',
    ],
    subItems: [
      {
        id: 61,
        label: 'Contas a Receber',
        link: '/jm/financeiro/contas-receber',
        parentId: 60,
        permissionKey: 'finance.accounts-receivable.view',
      },
      {
        id: 62,
        label: 'Contas a Pagar',
        link: '/jm/financeiro/contas-pagar',
        parentId: 60,
        permissionKey: 'finance.accounts-payable.view',
      },
      {
        id: 63,
        label: 'DRE',
        link: '/jm/financeiro/dre',
        parentId: 60,
        permissionKey: 'finance.reports.view',
      },
        {
          id: 64,
          label: 'Fluxo de Caixa',
          link: '/jm/financeiro/fluxo-caixa',
          parentId: 60,
          permissionKey: 'finance.cash-flow.view',
        },
      {
        id: 70,
        label: 'Comissoes',
        link: '/jm/financeiro/comissoes',
        parentId: 60,
        permissionKey: 'commercial.results.view',
      },
    ],
  },
  {
    id: 80,
    label: 'RH',
    icon: 'ph-user-gear',
    permissionKeys: [
      'hr.staff-control.view',
      'hr.absences.view',
      'hr.payroll.view',
      'hr.vacations.view',
      'hr.uniforms.view',
    ],
    subItems: [
      {
        id: 81,
        label: 'Colaboradores',
        link: '/jm/rh/controle-funcionarios',
        parentId: 80,
        permissionKey: 'hr.staff-control.view',
      },
      {
        id: 82,
        label: 'Controle de Faltas',
        link: '/jm/rh/controle-faltas',
        parentId: 80,
        permissionKey: 'hr.absences.view',
      },
      {
        id: 83,
        label: 'Folha de Pagamentos',
        link: '/jm/rh/folha-pagamentos',
        parentId: 80,
        permissionKey: 'hr.payroll.view',
      },
      {
        id: 84,
        label: 'Ferias',
        link: '/jm/rh/ferias',
        parentId: 80,
        permissionKey: 'hr.vacations.view',
      },
      {
        id: 85,
        label: 'Controle de Uniforme',
        link: '/jm/rh/controle-uniforme',
        parentId: 80,
        permissionKey: 'hr.uniforms.view',
      },
    ],
  },
  {
    id: 90,
    label: 'Administracao',
    icon: 'ph-gear-six',
    permissionKeys: [
      'admin.users.view',
      'admin.profiles.view',
      'admin.permissions.view',
      'admin.general-settings.view',
    ],
    subItems: [
      {
        id: 91,
        label: 'Gerais',
        link: '/jm/settings',
        parentId: 90,
        permissionKey: 'admin.general-settings.view',
      },
      {
        id: 92,
        label: 'Usuarios',
        parentId: 90,
        disabled: true,
        alwaysVisible: true,
        badge: 'Interno',
      },
      {
        id: 93,
        label: 'Perfis e Acessos',
        parentId: 90,
        disabled: true,
        alwaysVisible: true,
        badge: 'Interno',
      },
      {
        id: 94,
        label: 'Parametros do Sistema',
        parentId: 90,
        disabled: true,
        alwaysVisible: true,
        badge: 'Interno',
      },
    ],
  },
];
